- name: Configure nodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodeJS
  ansible.builtin.yum:
    name: nodeJS
    state: installed

- name: Run Pre-requisites
  ansible.builtin.import_tasks:
    name: app_prereq.yml

- name: Install nodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Install Schema mongodb
  ansible.builtin.import_tasks:
    name: schema_setup.yml

- name: Include SystemD
  ansible.builtin.import_tasks:
    name: systemd_setup.yml
